[package]
name = "index_vec"
version = "0.0.1-alpha"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
edition = "2018"
description = "Like `Vec` and `usize`, but with more type safety"
license = "MIT/Apache-2.0"
repository = "http://github.com/thomcc/index_vec"
keywords = ["newtype", "vec", "index", "indexed", "usize"]
categories = ["data-structures", "no-std", "rust-patterns"]
readme = "README.md"

[features]
example_generated = []
default = []

[dependencies]

[package.metadata.docs.rs]
features = ["example_generated"]
