version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - Run tests
      - Lint and check formatting
jobs:
  Run tests:
    docker:
      - image: circleci/rust:1.37.0

    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Test
          command: cargo test --all --verbose
      - run:
          name: Test (all features)
          command: cargo test --all --all-features --verbose

  Lint and check formatting:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustup component add clippy rustfmt
      - run: cargo fmt -- --version
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- --version
      - run: cargo clippy --all-features --all --all-targets -- -D warnings

